build: off
environment:
  CMAKE_GENERATOR_TOOLSET: "v140"
  matrix:
    # Python 2.7 is disabled due to not working
    #- PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"
      CMAKE_GENERATOR: "Visual Studio 14"
      CMAKE_GENERATOR_PLATFORM: "Win32"
    #- PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"
      CMAKE_GENERATOR: "Visual Studio 14 Win64"
      CMAKE_GENERATOR_PLATFORM: "x64"

configuration: Release
platform:
  - x64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - echo %PATH%
  - python --version
  - git submodule update --init
  - pip install -r requirements-dev.txt
  - pip install .

test_script:
  - pytest tests/test_basic_int.py
  - pytest tests/test_basic_str.py
  - pytest tests/test_cells_and_edges.py
  - pytest tests/test_collection_inputs.py
  - pytest tests/test_h3.py
  - pytest tests/test_memview_int.py
  - pytest tests/test_numpy_int.py
  - pytest tests/test_polyfill.py
  - pytest tests/test_to_multipoly.py
