name: coverage-lint

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: Coverage and Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]

      - name: Lint
        run: flake8 src/h3 setup.py tests

      - name: Pylint
        # As a test for visibility of API bindings, we want to ensure that pylint has no
        # `import-error` warnings for h3 imports.
        run: pylint --disable=all --enable=import-error tests/

      - name: Coverage
        run: |
          pip install Cython
          cythonize -i tests/cython_example.pyx
          pytest --cov=h3 --full-trace --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Copy Cython annotations to project dir
        run: |
          mkdir annotations
          cp _skbuild/*/cmake-build/src/h3/_cy/*.html ./annotations

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ./annotations
