name: coverage-lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Coverage and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.8

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]

      - name: Lint
        run: flake8 src/h3 setup.py tests

      - name: Pylint
        # As a test for visibility of API bindings, we want to ensure that pylint has no
        # `import-error` warnings for h3 imports.
        run: pylint --disable=all --enable=import-error tests/

      - name: Coverage
        run: pytest --cov=h3 --full-trace --cov-report=xml tests/*.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
