name: coverage-lint

on:
  push:
    branches: [master]

jobs:
  tests:
    name: Coverage and Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[test]

      - name: Run Linting
        uses: astral-sh/ruff-action@v1

      - name: Coverage
        run: |
          pip install cython
          cythonize tests/test_cython/cython_example.pyx
          pytest --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
