name: pr-coverage-lint

on:
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: Coverage and Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[test]

      - name: Run Linting
        uses: astral-sh/ruff-action@v1

      - name: Coverage
        run: |
          pip install cython
          cythonize tests/test_cython/cython_example.pyx
          pytest --cov-report=lcov

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          filter-changed-files: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage.lcov
