name: deploy_docs

# todo: we want to build on PRs, but keep it from pushing to deploy...

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.in
          pip install .[all]

      - name: Lint
        # run: flake8 --ignore=E501 h3.py
        run: flake8 src/h3

      # Build the book
      - name: Build the book
        # turn off warningiserror just for https://github.com/uber/h3-py/pull/283
        # jupyter-book build docs/ --warningiserror --keep-going --all
        run: |
          jupyter-book build docs/ --keep-going --all

  upload-docs:
    needs: [build-docs]
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true

    steps:
      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
