name: lint_and_coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  linting:
    name: Lint and Coverage
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.11'


      - name: Install from source
        run: uv sync --extra numpy

      - name: Run Linting
        uses: astral-sh/ruff-action@v3

      - name: Coverage Requirement - Library
        run: uv run pytest tests/test_lib --cov=h3 --cov=tests/test_lib --cov-fail-under=100

      - name: Coverage - Cython
        run: |
          uv run --with cython --with setuptools cythonize tests/test_cython/cython_example.pyx
          uv run pytest tests/test_cython --cov=tests/test_cython
