name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: Py${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '${{ matrix.python-version }}'

      ## Start Windows stuff
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        if: startsWith(matrix.os, 'windows')

      - name: Set Windows Compiler
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "CC=cl.exe" >> $GITHUB_ENV
          echo "CXX=cl.exe" >> $GITHUB_ENV
      ## End Windows stuff

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[test]

      - name: Tests
        run: |
          pip install cython
          cythonize tests/test_cython/cython_example.pyx
          pytest
