name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: Py${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '${{ matrix.python-version }}'

      - uses: extractions/setup-just@v2

      ## Start Windows stuff
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        if: startsWith(matrix.os, 'windows')

      - name: Set Windows Compiler
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "CC=cl.exe" >> $GITHUB_ENV
          echo "CXX=cl.exe" >> $GITHUB_ENV
      ## End Windows stuff

      - name: Install
        run: uv sync

      - name: Tests
        run: just ci-test

      - name: Cython Tests
        run: just ci-test-cython
